menu:
    Blog: /
    Archive: /archives/
    Weibo: https://weibo.com/u/1780200685
    GitHub: https://github.com/lgb1234a

favicon: /favicon.jpeg
logo: /favicon.jpeg

# Comment
# e.g disqus: seansun
disqus: chenyn
duoshuo:

# Analytics
# google-analytics:
# ga: UA-xxxxxxxx-x

# Copyright Infomation
startyear: 2018
